=== tompecina/bitwriter/src/cz/pecina/bin/bitwriter/bin-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:annotation>
    <xs:documentation>
      XML Schema pro BIN, version 1.0
      URL: http://www.pecina.cz/xsd/bin-1.0.xsd
      Author: Tomáš Pecina, tomas@pecina.cz
      License: GNU General Public License
    </xs:documentation>
  </xs:annotation>
  
  <xs:annotation>
    <xs:documentation>
      Containers
    </xs:documentation>
  </xs:annotation>

  <xs:element name="file">
    <xs:complexType>
      <xs:complexContent>
	<xs:extension base="base-loop">
	  <xs:attribute name="version" use="required" type="xs:NMTOKEN" fixed="1.0"/>
	</xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="loop">
    <xs:complexType>
      <xs:complexContent>
	<xs:extension base="base-loop">
	  <xs:attribute name="repeat" type="nonNegativeIntegerOrScript" default="1"/>
	</xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="base-loop">
    <xs:choice maxOccurs="unbounded">
      <xs:element ref="stream"/>
      <xs:group ref="freeVariable"/>
      <xs:element ref="loop"/>
      <xs:element ref="script"/>
    </xs:choice>
  </xs:complexType>

  <xs:element name="seq" type="seq"/>
  
  <xs:complexType name="seq" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:group ref="variable"/>
      <xs:element name="hex" type="radix"/>
      <xs:element name="dec" type="radix"/>
      <xs:element name="oct" type="radix"/>
      <xs:element name="bin" type="radix"/>
      <xs:element name="bits" type="radix"/>
      <xs:element name="float" type="radix"/>
      <xs:element name="double" type="radix"/>
      <xs:element name="text" type="text"/>
      <xs:element ref="random"/>
      <xs:element ref="include"/>
      <xs:element ref="seq"/>
      <xs:element ref="flush"/>
      <xs:element ref="script"/>
    </xs:choice>
    <xs:attribute name="repeat" type="nonNegativeIntegerOrScript" default="1"/>
  </xs:complexType>

  <xs:element name="stream">
    <xs:complexType mixed="true">
      <xs:complexContent>
	<xs:extension base="seq">
	  <xs:attribute name="width-in" type="positiveIntegerOrScript" default="8"/>
	  <xs:attribute name="width-out" type="positiveIntegerOrScript" default="8"/>
	  <xs:attribute name="endianness-in" type="endiannessOrScript" default="big"/>
	  <xs:attribute name="endianness-out" type="endiannessOrScript" default="big"/>
	  <xs:attribute name="width-aggregate-in" type="positiveIntegerOrScript" default="8"/>
	  <xs:attribute name="width-aggregate-out" type="positiveIntegerOrScript" default="8"/>
	  <xs:attribute name="reflect-in" type="booleanOrScript" default="false"/>
	  <xs:attribute name="reflect-out" type="booleanOrScript" default="false"/>
	  <xs:attribute name="discard" type="booleanOrScript" default="false"/>
	</xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="radix" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:group ref="variable"/>
      <xs:element ref="flush"/>
      <xs:element ref="script"/>
    </xs:choice>
    <xs:attribute name="repeat" type="nonNegativeIntegerOrScript" default="1"/>
  </xs:complexType>

  <xs:complexType name="text" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:group ref="variable"/>
      <xs:element ref="flush"/>
      <xs:element ref="script"/>
    </xs:choice>
    <xs:attribute name="repeat" type="nonNegativeIntegerOrScript" default="1"/>
    <xs:attribute name="trim" type="booleanOrScript" default="true"/>
    <xs:attribute name="charset" type="tokenOrScript" default="UTF-8"/>
  </xs:complexType>

  <xs:annotation>
    <xs:documentation>
      Variable elements
    </xs:documentation>
  </xs:annotation>

  <xs:group name="variable">
    <xs:choice>
      <xs:group ref="freeVariable"/>
      <xs:group ref="boundVariable"/>
    </xs:choice>
  </xs:group>
  
  <xs:group name="freeVariable">
    <xs:choice>
      <xs:element ref="set"/>
      <xs:element ref="reset"/>
      <xs:element ref="show"/>
      <xs:element ref="release"/>
      <xs:element ref="crc"/>
      <xs:element ref="parity"/>
      <xs:element ref="sum"/>
      <xs:element ref="digest"/>
    </xs:choice>
  </xs:group>
  
  <xs:group name="boundVariable">
    <xs:choice>
      <xs:element ref="put"/>
    </xs:choice>
  </xs:group>

  <xs:complexType name="variable">
    <xs:attribute name="name" use="required" type="variableNameOrScript"/>
  </xs:complexType>

  <xs:element name="set">
    <xs:complexType>
      <xs:complexContent>
  	<xs:extension base="variable">
  	  <xs:attribute name="value" type="integerOrScript"/>
  	  <xs:attribute name="on-stream-in" type="emptyOrIntegerOrScript"/>
  	  <xs:attribute name="on-aggregate-stream-in" type="emptyOrIntegerOrScript"/>
  	  <xs:attribute name="on-bitstream" type="emptyOrIntegerOrScript"/>
  	  <xs:attribute name="on-aggregate-stream-out" type="emptyOrIntegerOrScript"/>
  	  <xs:attribute name="on-stream-out" type="emptyOrIntegerOrScript"/>
  	  <xs:attribute name="on-output-stream" type="emptyOrIntegerOrScript"/>
  	</xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="reset" type="variable"/>

  <xs:element name="release" type="variable"/>

  <xs:element name="put">
    <xs:complexType>
      <xs:attribute name="name" type="variableNameOrScript"/>
      <xs:attribute name="value" type="integerOrScript"/>
      <xs:attribute name="type" type="variableTypeOrScript" default="stream-in"/>
      <xs:attribute name="reset" type="booleanOrScript" default="true"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="show">
    <xs:complexType>
      <xs:attribute name="name" type="variableNameOrScript"/>
      <xs:attribute name="value" type="integerOrScript"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="parity">
    <xs:complexType>
      <xs:complexContent>
  	<xs:extension base="variable">
  	  <xs:attribute name="type" type="variableTypeOrScript" default="bitstream"/>
  	  <xs:attribute name="model" type="parityModelOrScript" default="odd"/>
  	</xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="sum">
    <xs:complexType>
      <xs:complexContent>
  	<xs:extension base="variable">
  	  <xs:attribute name="type" type="variableTypeOrScript" default="stream-out"/>
  	  <xs:attribute name="width" type="positiveIntegerOrScript" default="8"/>
  	  <xs:attribute name="xor-in" type="integerOrScript" default="0"/>
  	  <xs:attribute name="xor-out" type="integerOrScript" default="0"/>
  	</xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="crc">
    <xs:complexType>
      <xs:complexContent>
  	<xs:extension base="variable">
  	  <xs:attribute name="type" type="variableTypeOrScript" default="stream-out"/>
  	  <xs:attribute name="model" type="tokenOrScript"/>
	  <xs:attribute name="notation" type="notationOrScript" default="normal"/>
  	  <xs:attribute name="width" type="positiveIntegerOrScript"/>
  	  <xs:attribute name="polynomial" type="positiveIntegerOrScript"/>
  	  <xs:attribute name="reflect-in" type="booleanOrScript" default="true"/>
  	  <xs:attribute name="xor-in" type="integerOrScript" default="-1"/>
  	  <xs:attribute name="reflect-out" type="booleanOrScript" default="true"/>
  	  <xs:attribute name="xor-out" type="integerOrScript" default="0"/>
  	</xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="digest">
    <xs:complexType>
      <xs:complexContent>
  	<xs:extension base="variable">
  	  <xs:attribute name="type" type="variableTypeOrScript" default="stream-out"/>
  	  <xs:attribute name="model" use="required" type="tokenOrScript"/>
  	</xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  
  <xs:annotation>
    <xs:documentation>
      Miscellaneous elements
    </xs:documentation>
  </xs:annotation>

  <xs:element name="flush" type="empty"/>

  <xs:element name="script">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="unmarkedScript">
	  <xs:attribute name="repeat" type="nonNegativeIntegerOrScript" default="1"/>
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="random">
    <xs:complexType>
      <xs:attribute name="width" type="positiveIntegerOrScript" default="8"/>
      <xs:attribute name="length" type="nonNegativeIntegerOrScript" default="1"/>
      <xs:attribute name="seed" type="integerOrScript" default="0"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="include">
    <xs:complexType>
      <xs:attribute name="repeat" type="nonNegativeIntegerOrScript" default="1"/>
      <xs:attribute name="location" use="required" type="tokenOrScript"/>
      <xs:attribute name="offset" type="nonNegativeIntegerOrScript" default="0"/>
      <xs:attribute name="length" type="nonNegativeIntegerOrScript" default="9223372036854775807"/>
    </xs:complexType>
  </xs:element>

  <xs:annotation>
    <xs:documentation>
      Types
    </xs:documentation>
  </xs:annotation>

  <xs:simpleType name="empty">
    <xs:restriction base="xs:string">
      <xs:enumeration value=""/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="integer">
    <xs:union memberTypes="hexInteger decInteger octInteger binInteger"/>
  </xs:simpleType>

  <xs:simpleType name="positiveInteger">
    <xs:union memberTypes="positiveHexInteger positiveDecInteger positiveOctInteger positiveBinInteger"/>
  </xs:simpleType>

  <xs:simpleType name="nonPositiveInteger">
    <xs:union memberTypes="zero negativeInteger"/>
  </xs:simpleType>

  <xs:simpleType name="zero">
    <xs:union memberTypes="hexZero decZero octZero binZero"/>
  </xs:simpleType>

  <xs:simpleType name="negativeInteger">
    <xs:union memberTypes="negativeHexInteger negativeDecInteger negativeOctInteger negativeBinInteger"/>
  </xs:simpleType>

  <xs:simpleType name="nonNegativeInteger">
    <xs:union memberTypes="zero positiveInteger"/>
  </xs:simpleType>

  <xs:simpleType name="hexInteger">
    <xs:union memberTypes="positiveHexInteger hexZero negativeHexInteger"/>
  </xs:simpleType>

  <xs:simpleType name="positiveHexInteger">
    <xs:restriction base="xs:NMTOKEN">
      <xs:pattern value="\+?0[xX]0*[1-9a-fA-F]+[0-9a-fA-F]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="hexZero">
    <xs:restriction base="xs:NMTOKEN">
      <xs:pattern value="[-+]?0[xX]0+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="negativeHexInteger">
    <xs:restriction base="xs:NMTOKEN">
      <xs:pattern value="-0[xX]0*[1-9a-fA-F]+[0-9a-fA-F]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="decInteger">
    <xs:union memberTypes="positiveDecInteger decZero negativeDecInteger"/>
  </xs:simpleType>
  
  <xs:simpleType name="positiveDecInteger">
    <xs:restriction base="xs:NMTOKEN">
      <xs:pattern value="\+?[1-9]\d*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="decZero">
    <xs:restriction base="xs:NMTOKEN">
      <xs:pattern value="[-+]?0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="negativeDecInteger">
    <xs:restriction base="xs:NMTOKEN">
      <xs:pattern value="-[1-9]\d*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="octInteger">
    <xs:union memberTypes="positiveOctInteger octZero negativeOctInteger"/>
  </xs:simpleType>
  
  <xs:simpleType name="positiveOctInteger">
    <xs:restriction base="xs:NMTOKEN">
      <xs:pattern value="\+?0+[1-7][0-7]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="octZero">
    <xs:restriction base="xs:NMTOKEN">
      <xs:pattern value="[-+]?0{2,}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="negativeOctInteger">
    <xs:restriction base="xs:NMTOKEN">
      <xs:pattern value="-0+[1-7][0-7]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="binInteger">
    <xs:union memberTypes="positiveBinInteger binZero negativeBinInteger"/>
  </xs:simpleType>

  <xs:simpleType name="positiveBinInteger">
    <xs:restriction base="xs:NMTOKEN">
      <xs:pattern value="\+?0[bB]0*1[01]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="binZero">
    <xs:restriction base="xs:NMTOKEN">
      <xs:pattern value="[-+]?0[bB]0+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="negativeBinInteger">
    <xs:restriction base="xs:NMTOKEN">
      <xs:pattern value="-0[bB]0*1[01]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="unmarkedScript">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
  
  <xs:simpleType name="markedScript">
    <xs:restriction base="xs:string">
      <xs:pattern value="\s*\{\{.*\}\}\s*"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="integerOrScript">
    <xs:union memberTypes="integer markedScript"/>
  </xs:simpleType>
  
  <xs:simpleType name="nonNegativeIntegerOrScript">
    <xs:union memberTypes="nonNegativeInteger markedScript"/>
  </xs:simpleType>

  <xs:simpleType name="positiveIntegerOrScript">
    <xs:union memberTypes="positiveInteger markedScript"/>
  </xs:simpleType>
  
  <xs:simpleType name="booleanOrScript">
    <xs:union memberTypes="xs:boolean markedScript"/>
  </xs:simpleType>

  <xs:simpleType name="endianness">
    <xs:restriction base="xs:NCName">
      <xs:enumeration value="big"/>
      <xs:enumeration value="little"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="endiannessOrScript">
    <xs:union memberTypes="endianness markedScript"/>
  </xs:simpleType>
  
  <xs:simpleType name="variableName">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-zA-Z_$][a-zA-Z\d_$]*"/>
    </xs:restriction>
  </xs:simpleType>
    
  <xs:simpleType name="variableNameOrScript">
    <xs:union memberTypes="variableName markedScript"/>
  </xs:simpleType>

  <xs:simpleType name="variableType">
    <xs:restriction base="xs:NCName">
      <xs:enumeration value="stream-in"/>
      <xs:enumeration value="aggregate-stream-in"/>
      <xs:enumeration value="bitstream"/>
      <xs:enumeration value="aggregate-stream-out"/>
      <xs:enumeration value="stream-out"/>
      <xs:enumeration value="output-stream"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="variableTypeOrScript">
    <xs:union memberTypes="variableType markedScript"/>
  </xs:simpleType>
  
  <xs:simpleType name="tokenOrScript">
    <xs:union memberTypes="xs:token markedScript"/>
  </xs:simpleType>
  
  <xs:simpleType name="parityModel">
    <xs:restriction base="xs:NCName">
      <xs:enumeration value="even"/>
      <xs:enumeration value="odd"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="parityModelOrScript">
    <xs:union memberTypes="parityModel markedScript"/>
  </xs:simpleType>

  <xs:simpleType name="emptyOrIntegerOrScript">
    <xs:union memberTypes="empty integer markedScript"/>
  </xs:simpleType>

  <xs:simpleType name="notation">
    <xs:restriction base="xs:NCName">
      <xs:enumeration value="normal"/>
      <xs:enumeration value="full"/>
      <xs:enumeration value="reversed"/>
      <xs:enumeration value="koopman"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="notationOrScript">
    <xs:union memberTypes="notation markedScript"/>
  </xs:simpleType>
  
</xs:schema>

=== tompecina/bitwriter/src/test/resources/cz/pecina/bin/bitwriter/input/VariableElement-process-11.xml
<?xml version="1.0" encoding="UTF-8"?>
<file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.pecina.cz/xsd/bin-1.0.xsd" version="1.0">
  <stream>
    <set name="n" value="1"/>
    <sum name="s" width="32"/>
    <dec repeat="100">
      {{n++}}
    </dec>
  </stream>
  <stream width-in="32">
    <put name="s"/>
  </stream>
  <stream>
    <hex repeat="8">
      ee
    </hex>
  </stream>
  <stream repeat="20">
    <sum name="s" width="1" type="bitstream"/>
    <parity name="p" model="even" type="bitstream"/>
    <dec repeat="14">
      {{n = ((n * 1664525) + 1013904223) % 0x100000000; n}}
    </dec>
    <release name="s"/>
    <release name="p"/>
    <put name="s"/>
    <put name="p"/>
  </stream>
  <stream>
    <hex repeat="16">
      ee
    </hex>
  </stream>
  <stream repeat="20">
    <sum name="s" width="1" type="bitstream"/>
    <parity name="p" model="odd" type="bitstream"/>
    <dec repeat="14">
      {{n = ((n * 1664525) + 1013904223) % 0x100000000; n}}
    </dec>
    <release name="s"/>
    <release name="p"/>
    <put name="s"/>
    <put name="p"/>
  </stream>
</file>

=== tompecina/bitwriter/src/test/resources/cz/pecina/bin/bitwriter/input/Crc-Crc10-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.pecina.cz/xsd/bin-1.0.xsd" version="1.0">
  <stream>
    <crc name="c" model="CRC-10"/>
    <hex>
      116A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A00AF
    </hex>
  </stream>
  <stream width-in="10">
    <put name="c"/>
  </stream>
  <stream repeat="14">
    0xee
  </stream>
  <stream>
    <crc name="c" model="CRC-10"/>
    <hex>
      1801AAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A02AC
    </hex>
  </stream>
  <stream width-in="10">
    <put name="c"/>
  </stream>
  <stream repeat="14">
    0xee
  </stream>
  <stream>
    <crc name="c" model="CRC-10"/>
    <hex>
      0A0B0C0D0E0F0000000000000000000000000000000000000000000000000000000000000000000000000000000001F6
    </hex>
  </stream>
  <stream width-in="10">
    <put name="c"/>
  </stream>
  <stream repeat="14">
    0xee
  </stream>
  <stream>
    <crc name="c" model="CRC-10"/>
    <hex>
      11111111111111111111000000000000000000000000000000000000000000000000000000000000000000000000016B
    </hex>
  </stream>
  <stream width-in="10">
    <put name="c"/>
  </stream>
  <stream repeat="14">
    0xee
  </stream>
  <stream>
    <crc name="c" model="CRC-10"/>
    <hex>
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF030F
    </hex>
  </stream>
  <stream width-in="10">
    <put name="c"/>
  </stream>
  <stream repeat="14">
    0xee
  </stream>
  <stream>
    <crc name="c" model="CRC-10"/>
    <hex>
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF030F
    </hex>
  </stream>
  <stream width-in="10">
    <put name="c"/>
  </stream>
  <stream repeat="14">
    0xee
  </stream>
  <stream>
    <crc name="c" model="CRC-10"/>
    <hex>
      1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901202ED
    </hex>
  </stream>
  <stream width-in="10">
    <put name="c"/>
  </stream>
  <stream repeat="14">
    0xee
  </stream>
  <stream>
    <crc name="c" model="CRC-10"/>
    <hex>
      106A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A03B9
    </hex>
  </stream>
  <stream width-in="10">
    <put name="c"/>
  </stream>
  <stream repeat="14">
    0xee
  </stream>
  <stream>
    <crc name="c" model="CRC-10"/>
    <hex>
      180100000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000000000000000000000000006A6A6A6A6A6A6A6A004A
    </hex>
  </stream>
  <stream width-in="10">
    <put name="c"/>
  </stream>
  <stream repeat="14">
    0xee
  </stream>
</file>

=== tompecina/bitwriter/src/test/resources/cz/pecina/bin/bitwriter/input/Util-extractIntAttribute-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.pecina.cz/xsd/bin-1.0.xsd" version="1.0">
  <stream>1 2</stream>
  <stream repeat="2">0x55</stream>
  <stream repeat="0x2">0xaa</stream>
  <stream repeat="02">0x33</stream>
  <stream repeat="0b10">0xcc</stream>
  <stream repeat="{{1+1}}">1</stream>
  <stream repeat="{{BigInteger.valueOf(2)}}">2</stream>
  <stream repeat="0">3</stream>
  <stream width-out="8">4</stream>
</file>

=== tompecina/bitwriter/src/test/resources/cz/pecina/bin/bitwriter/input/Util-extractStringArrayAttribute-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.pecina.cz/xsd/bin-1.0.xsd" version="1.0">
  <stream>
    <hex>
      <set name="c0" value="0x55"/>
      <put name=" c0"/>
    </hex>
  </stream>
  <stream width-aggregate-in="32" endianness-in="big">
    <hex>
      11 22 33 44
    </hex>
  </stream>
  <stream width-aggregate-in="32" endianness-in="little">
    <hex>
      11 22 33 44
    </hex>
  </stream>
  <stream width-aggregate-in="32">
    <hex>
      11 22 33 44
    </hex>
  </stream>
</file>

=== tompecina/bitwriter/src/test/resources/cz/pecina/bin/bitwriter/input/VariableElement-process-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.pecina.cz/xsd/bin-1.0.xsd" version="1.0">
  <stream>
    <crc name="x1" model="CRC-32Q"/>
    0x55
    <set name="x2" value="{{x1}}"/>
    <set name="x1"/>
    0xaa
    <put name="x1"/>
    <put name="x2"/>
    <crc name="x1" model="CRC-32Q"/>
    0x55
    <set name="x2" value="{{x1}}"/>
    0xaa
    <put name="x1"/>
    <put name="x2"/>
  </stream>
</file>

=== tompecina/bitwriter/src/test/resources/cz/pecina/bin/bitwriter/input/Util-consolidate-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.pecina.cz/xsd/bin-1.0.xsd" version="1.0">
  <stream>1<!-- test -->2</stream>
  <stream>1 <!-- test -->2</stream>
  <stream>1<!-- test --> 2</stream>
  <stream> 1<!-- test -->2</stream>
  <stream> 1 <!-- test -->2</stream>
  <stream> 1<!-- test --> 2</stream>
  <stream> 1<!-- test -->2 </stream>
  <stream> 1 <!-- test -->2 </stream>
  <stream> 1<!-- test --> 2 </stream>
  <stream>1<?php phpinfo(); ?>2</stream>
  <stream>1 <?php phpinfo(); ?>2</stream>
  <stream>1<?php phpinfo(); ?> 2</stream>
  <stream> 1<?php phpinfo(); ?>2</stream>
  <stream> 1 <?php phpinfo(); ?>2</stream>
  <stream> 1<?php phpinfo(); ?> 2</stream>
  <stream> 1<?php phpinfo(); ?>2 </stream>
  <stream> 1 <?php phpinfo(); ?>2 </stream>
  <stream> 1<?php phpinfo(); ?> 2 </stream>
  <stream><reset name="n"/>1<!-- test -->2</stream>
  <stream><reset name="n"/>1 <!-- test -->2</stream>
  <stream><reset name="n"/>1<!-- test --> 2</stream>
  <stream><reset name="n"/> 1<!-- test -->2</stream>
  <stream><reset name="n"/> 1 <!-- test -->2</stream>
  <stream><reset name="n"/> 1<!-- test --> 2</stream>
  <stream><reset name="n"/> 1<!-- test -->2 </stream>
  <stream><reset name="n"/> 1 <!-- test -->2 </stream>
  <stream><reset name="n"/> 1<!-- test --> 2 </stream>
  <stream><reset name="n"/>1<?php phpinfo(); ?>2</stream>
  <stream><reset name="n"/>1 <?php phpinfo(); ?>2</stream>
  <stream><reset name="n"/>1<?php phpinfo(); ?> 2</stream>
  <stream><reset name="n"/> 1<?php phpinfo(); ?>2</stream>
  <stream><reset name="n"/> 1 <?php phpinfo(); ?>2</stream>
  <stream><reset name="n"/> 1<?php phpinfo(); ?> 2</stream>
  <stream><reset name="n"/> 1<?php phpinfo(); ?>2 </stream>
  <stream><reset name="n"/> 1 <?php phpinfo(); ?>2 </stream>
  <stream><reset name="n"/> 1<?php phpinfo(); ?> 2 </stream>
  <stream>1<![CDATA[2]]>3</stream>
  <stream>1
  <![CDATA[2]]>3</stream>
  <stream>1<![CDATA[2]]>
  3</stream>
  <stream>1<!-- test -->2</stream>
  <stream>1
  <!-- test -->2</stream>
  <stream>1<!-- test -->
  2</stream>
  <stream>
  1<!-- test -->2</stream>
  <stream>
  1 <!-- test -->2</stream>
  <stream>
    1<!-- test -->
  2</stream>
  <stream>
    1<!-- test -->2
  </stream>
  <stream>
    1 <!-- test -->2
  </stream>
  <stream>
    1<!-- test -->
    2
  </stream>
  <stream>1<?php phpinfo(); ?>2</stream>
  <stream>1
  <?php phpinfo(); ?>2</stream>
  <stream>1<?php phpinfo(); ?>
  2</stream>
  <stream>
  1<?php phpinfo(); ?>2</stream>
  <stream>
  1 <?php phpinfo(); ?>2</stream>
  <stream>
    1<?php phpinfo(); ?>
  2</stream>
  <stream>
    1<?php phpinfo(); ?>2
  </stream>
  <stream>
    1 <?php phpinfo(); ?>2
  </stream>
  <stream>
    1<?php phpinfo(); ?>
    2
  </stream>
  <stream><reset name="n"/>1<!-- test -->2</stream>
  <stream><reset name="n"/>1
  <!-- test -->2</stream>
  <stream><reset name="n"/>1<!-- test -->
  2</stream>
  <stream><reset name="n"/>
  1<!-- test -->2</stream>
  <stream><reset name="n"/>
  1 <!-- test -->2</stream>
  <stream><reset name="n"/>
  1<!-- test -->
  2</stream>
  <stream><reset name="n"/>
  1<!-- test -->2
  </stream>
  <stream><reset name="n"/>
  1 <!-- test -->2
  </stream>
  <stream><reset name="n"/>
  1<!-- test -->
  2
  </stream>
  <stream><reset name="n"/>1<?php phpinfo(); ?>2</stream>
  <stream><reset name="n"/>1
  <?php phpinfo(); ?>2</stream>
  <stream><reset name="n"/>1<?php phpinfo(); ?>
  2</stream>
  <stream><reset name="n"/>
  1<?php phpinfo(); ?>2</stream>
  <stream><reset name="n"/>
  1
  <?php phpinfo(); ?>2</stream>
  <stream><reset name="n"/>
  1<?php phpinfo(); ?>
  2</stream>
  <stream><reset name="n"/>
  1<?php phpinfo(); ?>2
  </stream>
  <stream><reset name="n"/>
  1
  <?php phpinfo(); ?>2
  </stream>
  <stream><reset name="n"/>
  1<?php phpinfo(); ?>
  2
  </stream>
  <stream>1<![CDATA[2]]>3</stream>
  <stream>1
  <![CDATA[2]]>3</stream>
  <stream>1<![CDATA[2]]>
  3</stream>
  <stream>{{ if (1 &lt; 2) 0x55; else 0xee; }}</stream>
</file>

=== tompecina/bitwriter/src/test/resources/cz/pecina/bin/bitwriter/input/Crc-Crc16En13757-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.pecina.cz/xsd/bin-1.0.xsd" version="1.0">
  <stream>
    <crc name="c" model="CRC-16/EN-13757"/>
    <reset name="i"/>
    <hex>
      ffff
    </hex>
  </stream>
  <stream width-in="16">
    <put name="c"/>
  </stream>
  <stream repeat="12">
    0xee
  </stream>
  <stream>
    <crc name="c" model="CRC-16/EN-13757"/>
    <reset name="i"/>
    <hex>
      780B13436587
      1E6D
    </hex>
  </stream>
  <stream width-in="16">
    <put name="c"/>
  </stream>
  <stream repeat="6">
    0xee
  </stream>
  <stream>
    <crc name="c" model="CRC-16/EN-13757"/>
    <reset name="i"/>
    <hex>
      07400001AAAA0000
      363E
    </hex>
  </stream>
  <stream width-in="16">
    <put name="c"/>
  </stream>
  <stream repeat="4">
    0xee
  </stream>
</file>

=== tompecina/bitwriter/src/test/resources/cz/pecina/bin/bitwriter/input/VariableElement-setVariableType-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.pecina.cz/xsd/bin-1.0.xsd" version="1.0">
  <stream width-in="16" width-aggregate-in="32" width-aggregate-out="0x80">
    <crc name="c1" model="crc-64/xz" type="stream-in"/>
    <crc name="c2" model="crc-64/xz" type="aggregate-stream-in"/>
    <crc name="c3" model="crc-64/xz" type="bitstream"/>
    <crc name="c4" model="crc-64/xz" type="aggregate-stream-out"/>
    <crc name="c5" model="crc-64/xz" type="stream-out"/>
    <crc name="c6" model="crc-64/xz" type="output-stream"/>
    <hex repeat="8">
      31
    </hex>
    <release name="c1"/>
    <release name="c2"/>
    <release name="c3"/>
    <release name="c4"/>
    <release name="c5"/>
    <release name="c6"/>
    <put name="c1" type="aggregate-stream-out"/>
    <put name="c2" type="aggregate-stream-out"/>
    <put name="c3" type="aggregate-stream-out"/>
    <put name="c4" type="aggregate-stream-out"/>
    <put name="c5" type="aggregate-stream-out"/>
    <put name="c6" type="aggregate-stream-out"/>
  </stream>
</file>
